// settingSlice.ts
import { createSlice } from "@reduxjs/toolkit";
import { Setting } from "../../types";

// Initial state of the settings slice
const settingInitialState: Setting = {
  showNavBar: true,
  showFooter: true,
};

// Create the settings slice to manage UI-related state (e.g., navigation bar visibility)
const settingSlice = createSlice({
  name: "setting", // Unique name for the slice
  initialState: settingInitialState,
  reducers: {
    /**
     * Toggles the visibility of the navigation bar.
     * If it's currently shown, it will be hidden and vice versa.
     */
    toggleNavBar: (state) => {
      state.showNavBar = !state.showNavBar;
    },

    /**
     * Explicitly hides the navigation bar regardless of current state.
     */
    hideNavBar: (state) => {
      state.showNavBar = false;
    },

    /**
     * Explicitly shows the navigation bar regardless of current state.
     */
    showNavBar: (state) => {
      state.showNavBar = true;
    },

    /**
     * Toggle the visisbility of the footer
     */
    toogleFooter: (state) => {
      state.showFooter = !state.showFooter;
    },

    /**
     * Explicitly hides the footer regardless of current state.
     */
    hideFooter: (state) => {
      state.showFooter = false;
    },

    /**
     * Explicitly shows the footer regardless of current state.
     */
    showFooter: (state) => {
      state.showFooter = true;
    },
  },
});

// Export the actions generated by createSlice
export const {
  toggleNavBar,
  hideNavBar,
  showNavBar,
  hideFooter,
  showFooter,
  toogleFooter,
} = settingSlice.actions;

// Export the reducer to be used in the Redux store
export default settingSlice.reducer;
