// settingSlice.ts
import { createSlice} from "@reduxjs/toolkit";
import { Setting } from "../../types";



// Initial state of the settings slice
const settingInitialState: Setting = {
  showNavBar: true,
};

// Create the settings slice to manage UI-related state (e.g., navigation bar visibility)
const settingSlice = createSlice({
  name: "setting", // Unique name for the slice
  initialState: settingInitialState,
  reducers: {
    /**
     * Toggles the visibility of the navigation bar.
     * If it's currently shown, it will be hidden and vice versa.
     */
    toggleNavBar: (state) => {
      state.showNavBar = !state.showNavBar;
    },

    /**
     * Explicitly hides the navigation bar regardless of current state.
     */
    hideNavBar: (state) => {
      state.showNavBar = false;
    },

      /**
     * Explicitly shows the navigation bar regardless of current state.
     */
    showNavBar: (state) => {
      state.showNavBar = true;
    },
  },
});

// Export the actions generated by createSlice
export const { toggleNavBar, hideNavBar, showNavBar } = settingSlice.actions;

// Export the reducer to be used in the Redux store
export default settingSlice.reducer;
